services:
  app:
    build: .
    container_name: securefile-app
    depends_on:
      - postgres
      - localstack
    environment:
      DB_URL: jdbc:postgresql://postgres:5433/securefile
      DB_USERNAME: admin
      DB_PASSWORD: admin
      SECUREFILE_JWT_SECRET: local-dev-jwt-secret-change-me
      SECUREFILE_JWT_TTL_MINUTES: "5"
      SECUREFILE_JWT_REFRESH_SECRET: local-dev-jwt-refresh-secret-change-me
      SECUREFILE_JWT_REFRESH_TTL_MINUTES: "10080"
      SECUREFILE_JWT_ISSUER: securefile-auth-local
      SECUREFILE_JWT_AUDIENCE: securefile-api-local
      SECUREFILE_DOWNLOAD_LINK_SECRET: local-dev-download-link-secret-change-me
      SECUREFILE_S3_ENDPOINT: http://localstack:4566
      SECUREFILE_S3_REGION: us-east-1
      SECUREFILE_S3_BUCKET: securefile-statements
      SECUREFILE_S3_ACCESS_KEY: test
      SECUREFILE_S3_SECRET_KEY: test
      SECUREFILE_S3_PATH_STYLE_ACCESS_ENABLED: "true"
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16
    container_name: securefile-postgres
    environment:
      POSTGRES_DB: securefile
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - securefile-postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/db/data/001_create_all_tables.sql:/docker-entrypoint-initdb.d/001_create_all_tables.sql:ro
      - ./src/main/resources/db/data/002_seed_all_tables.sql:/docker-entrypoint-initdb.d/002_seed_all_tables.sql:ro
      - ./src/main/resources/db/data/003_seed_all_tables_for_customer_1.sql:/docker-entrypoint-initdb.d/003_seed_all_tables_for_customer_1.sql:ro
      - ./src/main/resources/db/data/004_seed_all_tables_for_customer_2.sql:/docker-entrypoint-initdb.d/004_seed_all_tables_for_customer_2.sql:ro
      - ./src/main/resources/db/data/005_seed_all_tables_for_customer_3.sql:/docker-entrypoint-initdb.d/005_seed_all_tables_for_customer_3.sql:ro

  localstack:
    image: localstack/localstack:4
    container_name: securefile-localstack
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: "1"
      PERSISTENCE: "1"
      SECUREFILE_S3_BUCKET: securefile-statements
    ports:
      - "4566:4566"
    volumes:
      - securefile-localstack-data:/var/lib/localstack
      - ./docker/localstack/init/01-create-bucket.sh:/etc/localstack/init/ready.d/01-create-bucket.sh:ro

volumes:
  securefile-postgres-data:
  securefile-localstack-data:
