spring:
  application:
    name: securefile
  datasource:
    url: jdbc:postgresql://localhost:5432/securefile
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
  lifecycle:
    timeout-per-shutdown-phase: 20s

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

securefile:
  s3:
    endpoint: http://localhost:4566
    region: us-east-1
    bucket: securefile-statements
    access-key: test
    secret-key: test
    path-style-access-enabled: true
