spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/securefile
    username: admin
    password: admin

securefile:
  jwt:
    secret: local-dev-jwt-secret-change-me
    ttl-minutes: 5
    refresh-secret: local-dev-jwt-refresh-secret-change-me
    refresh-ttl-minutes: 10080
  download-link:
    secret: local-dev-download-link-secret-change-me
  s3:
    endpoint: http://localhost:4566
    region: us-east-1
    bucket: securefile-statements
    access-key: test
    secret-key: test
    path-style-access-enabled: true
