spring:
  application:
    name: securefile
  datasource:
    url: jdbc:postgresql://localhost:5432/securefile
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none

securefile:
  s3:
    endpoint: http://localhost:4566
    region: us-east-1
    bucket: securefile-statements
    access-key: test
    secret-key: test
    path-style-access-enabled: true

